# -*- coding: utf-8 -*-
"""Total Token Distribution by Tea Books in Tang, Song, and Ming Dynasties.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19sQh4-OC6upztP4fQWHcCcnuVisjU5xj
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.ticker import MaxNLocator

# Create the DataFrame from your data
data = pd.DataFrame([
    # Tang Dynasty
    {"Dynasty": "Tang", "BookTitle": "Chajing", "ChapterTitle": "The Origin of Tea", "TokenCount": 364},
    {"Dynasty": "Tang", "BookTitle": "Chajing", "ChapterTitle": "The Tools for Tea Production", "TokenCount": 615},
    {"Dynasty": "Tang", "BookTitle": "Chajing", "ChapterTitle": "The Manufacturing of Tea", "TokenCount": 381},
    {"Dynasty": "Tang", "BookTitle": "Chajing", "ChapterTitle": "The Utensils for Tea", "TokenCount": 1847},
    {"Dynasty": "Tang", "BookTitle": "Chajing", "ChapterTitle": "The Brewing of Tea", "TokenCount": 813},
    {"Dynasty": "Tang", "BookTitle": "Chajing", "ChapterTitle": "The Drinking of Tea", "TokenCount": 481},
    {"Dynasty": "Tang", "BookTitle": "Chajing", "ChapterTitle": "The Stories about Tea", "TokenCount": 2805},
    {"Dynasty": "Tang", "BookTitle": "Chajing", "ChapterTitle": "The Origins of Tea Producing Areas", "TokenCount": 218},
    {"Dynasty": "Tang", "BookTitle": "Chajing", "ChapterTitle": "The Essentials of Tea", "TokenCount": 287},
    {"Dynasty": "Tang", "BookTitle": "Shiliupintang", "ChapterTitle": "The First Grade: De Yi Tang", "TokenCount": 60},
    {"Dynasty": "Tang", "BookTitle": "Shiliupintang", "ChapterTitle": "The Second Grade: Ying Tang", "TokenCount": 34},
    {"Dynasty": "Tang", "BookTitle": "Shiliupintang", "ChapterTitle": "The Third Grade: Bai Shou Tang", "TokenCount": 63},
    {"Dynasty": "Tang", "BookTitle": "Shiliupintang", "ChapterTitle": "The Fourth Grade: Zhong Tang", "TokenCount": 65},
    {"Dynasty": "Tang", "BookTitle": "Shiliupintang", "ChapterTitle": "The Fifth Grade: Duan Mai Tang", "TokenCount": 67},
    {"Dynasty": "Tang", "BookTitle": "Shiliupintang", "ChapterTitle": "The Sixth Grade: Da Zhuang Tang", "TokenCount": 63},
    {"Dynasty": "Tang", "BookTitle": "Shiliupintang", "ChapterTitle": "The Seventh Grade: Fu Gui Tang", "TokenCount": 55},
    {"Dynasty": "Tang", "BookTitle": "Shiliupintang", "ChapterTitle": "The Eighth Grade: Xiu Bi Tang", "TokenCount": 34},
    {"Dynasty": "Tang", "BookTitle": "Shiliupintang", "ChapterTitle": "The Ninth Grade: Yan Yi Tang", "TokenCount": 50},
    {"Dynasty": "Tang", "BookTitle": "Shiliupintang", "ChapterTitle": "The Tenth Grade: Chan Kou Tang", "TokenCount": 48},
    {"Dynasty": "Tang", "BookTitle": "Shiliupintang", "ChapterTitle": "The Eleventh Grade: Jian Jia Tang", "TokenCount": 49},
    {"Dynasty": "Tang", "BookTitle": "Shiliupintang", "ChapterTitle": "The Twelfth Grade: Fa Lv Tang", "TokenCount": 52},
    {"Dynasty": "Tang", "BookTitle": "Shiliupintang", "ChapterTitle": "The Thirteenth Grade: Yi Mian Tang", "TokenCount": 43},
    {"Dynasty": "Tang", "BookTitle": "Shiliupintang", "ChapterTitle": "The Fourteenth Grade: Xiao Tang", "TokenCount": 30},
    {"Dynasty": "Tang", "BookTitle": "Shiliupintang", "ChapterTitle": "The Fifteenth Grade: Zei Tang", "TokenCount": 39},
    {"Dynasty": "Tang", "BookTitle": "Shiliupintang", "ChapterTitle": "The Sixteenth Grade: Mo Tang", "TokenCount": 47},

    # Song Dynasty
    {"Dynasty": "Song", "BookTitle": "Daguanchalun", "ChapterTitle": "Real estate", "TokenCount": 77},
    {"Dynasty": "Song", "BookTitle": "Daguanchalun", "ChapterTitle": "Timing", "TokenCount": 108},
    {"Dynasty": "Song", "BookTitle": "Daguanchalun", "ChapterTitle": "Selection and picking", "TokenCount": 120},
    {"Dynasty": "Song", "BookTitle": "Daguanchalun", "ChapterTitle": "Steaming and pressing", "TokenCount": 91},
    {"Dynasty": "Song", "BookTitle": "Daguanchalun", "ChapterTitle": "Manufacturing", "TokenCount": 96},
    {"Dynasty": "Song", "BookTitle": "Daguanchalun", "ChapterTitle": "Appraisal and discrimination", "TokenCount": 230},
    {"Dynasty": "Song", "BookTitle": "Daguanchalun", "ChapterTitle": "White tea", "TokenCount": 133},
    {"Dynasty": "Song", "BookTitle": "Daguanchalun", "ChapterTitle": "Grinding with a sieve", "TokenCount": 151},
    {"Dynasty": "Song", "BookTitle": "Daguanchalun", "ChapterTitle": "Tea bowl", "TokenCount": 102},
    {"Dynasty": "Song", "BookTitle": "Daguanchalun", "ChapterTitle": "Tea whisk", "TokenCount": 69},
    {"Dynasty": "Song", "BookTitle": "Daguanchalun", "ChapterTitle": "Bottle", "TokenCount": 86},
    {"Dynasty": "Song", "BookTitle": "Daguanchalun", "ChapterTitle": "Spoon", "TokenCount": 43},
    {"Dynasty": "Song", "BookTitle": "Daguanchalun", "ChapterTitle": "Water", "TokenCount": 130},
    {"Dynasty": "Song", "BookTitle": "Daguanchalun", "ChapterTitle": "Infusion", "TokenCount": 473},
    {"Dynasty": "Song", "BookTitle": "Daguanchalun", "ChapterTitle": "Taste", "TokenCount": 122},
    {"Dynasty": "Song", "BookTitle": "Daguanchalun", "ChapterTitle": "Smell", "TokenCount": 66},
    {"Dynasty": "Song", "BookTitle": "Daguanchalun", "ChapterTitle": "Color", "TokenCount": 102},
    {"Dynasty": "Song", "BookTitle": "Daguanchalun", "ChapterTitle": "Storage and roasting", "TokenCount": 228},
    {"Dynasty": "Song", "BookTitle": "Daguanchalun", "ChapterTitle": "Product name", "TokenCount": 190},
    {"Dynasty": "Song", "BookTitle": "Daguanchalun", "ChapterTitle": "External roasting", "TokenCount": 284},
    {"Dynasty": "Song", "BookTitle": "Chalu", "ChapterTitle": "Color", "TokenCount": 91},
    {"Dynasty": "Song", "BookTitle": "Chalu", "ChapterTitle": "Smell", "TokenCount": 61},
    {"Dynasty": "Song", "BookTitle": "Chalu", "ChapterTitle": "Taste", "TokenCount": 69},
    {"Dynasty": "Song", "BookTitle": "Chalu", "ChapterTitle": "Stored tea", "TokenCount": 63},
    {"Dynasty": "Song", "BookTitle": "Chalu", "ChapterTitle": "Roasted tea", "TokenCount": 61},
    {"Dynasty": "Song", "BookTitle": "Chalu", "ChapterTitle": "Milled tea", "TokenCount": 37},
    {"Dynasty": "Song", "BookTitle": "Chalu", "ChapterTitle": "Sieved tea", "TokenCount": 11},
    {"Dynasty": "Song", "BookTitle": "Chalu", "ChapterTitle": "Waiting for the water to boil", "TokenCount": 49},
    {"Dynasty": "Song", "BookTitle": "Chalu", "ChapterTitle": "Heating the tea bowl", "TokenCount": 18},
    {"Dynasty": "Song", "BookTitle": "Chalu", "ChapterTitle": "Making powdered tea", "TokenCount": 105},
    {"Dynasty": "Song", "BookTitle": "Chalu", "ChapterTitle": "Tea roasting oven", "TokenCount": 55},
    {"Dynasty": "Song", "BookTitle": "Chalu", "ChapterTitle": "Tea basket", "TokenCount": 27},
    {"Dynasty": "Song", "BookTitle": "Chalu", "ChapterTitle": "Anvil and mallet", "TokenCount": 25},
    {"Dynasty": "Song", "BookTitle": "Chalu", "ChapterTitle": "Tea lock", "TokenCount": 14},
    {"Dynasty": "Song", "BookTitle": "Chalu", "ChapterTitle": "Tea mill", "TokenCount": 28},
    {"Dynasty": "Song", "BookTitle": "Chalu", "ChapterTitle": "Tea sieve", "TokenCount": 30},
    {"Dynasty": "Song", "BookTitle": "Chalu", "ChapterTitle": "Tea bowl", "TokenCount": 68},
    {"Dynasty": "Song", "BookTitle": "Chalu", "ChapterTitle": "Tea spoon", "TokenCount": 33},
    {"Dynasty": "Song", "BookTitle": "Chalu", "ChapterTitle": "Hot water bottle", "TokenCount": 36},
    {"Dynasty": "Song", "BookTitle": "Pinchayaolu", "ChapterTitle": "General Introduction", "TokenCount": 316},
    {"Dynasty": "Song", "BookTitle": "Pinchayaolu", "ChapterTitle": "Picking and manufacturing at an improper time", "TokenCount": 188},
    {"Dynasty": "Song", "BookTitle": "Pinchayaolu", "ChapterTitle": "Mixing in white lotuses and stolen leaves", "TokenCount": 189},
    {"Dynasty": "Song", "BookTitle": "Pinchayaolu", "ChapterTitle": "Adding impurities", "TokenCount": 139},
    {"Dynasty": "Song", "BookTitle": "Pinchayaolu", "ChapterTitle": "Insufficient steaming", "TokenCount": 89},
    {"Dynasty": "Song", "BookTitle": "Pinchayaolu", "ChapterTitle": "Over-steaming", "TokenCount": 77},
    {"Dynasty": "Song", "BookTitle": "Pinchayaolu", "ChapterTitle": "Burnt pot", "TokenCount": 63},
    {"Dynasty": "Song", "BookTitle": "Pinchayaolu", "ChapterTitle": "Pressed yellow", "TokenCount": 129},
    {"Dynasty": "Song", "BookTitle": "Pinchayaolu", "ChapterTitle": "Soaked paste", "TokenCount": 70},
    {"Dynasty": "Song", "BookTitle": "Pinchayaolu", "ChapterTitle": "Damaged roasting", "TokenCount": 115},
    {"Dynasty": "Song", "BookTitle": "Pinchayaolu", "ChapterTitle": "Distinguishing the sources of the gully and the Shaxi River", "TokenCount": 331},
    {"Dynasty": "Song", "BookTitle": "Pinchayaolu", "ChapterTitle": "Post-discussion", "TokenCount": 294},

    # Ming Dynasty
    {"Dynasty": "Ming", "BookTitle": "Chapu", "ChapterTitle": "Tasting tea", "TokenCount": 99},
    {"Dynasty": "Ming", "BookTitle": "Chapu", "ChapterTitle": "Collecting tea", "TokenCount": 157},
    {"Dynasty": "Ming", "BookTitle": "Chapu", "ChapterTitle": "Making powdered tea", "TokenCount": 127},
    {"Dynasty": "Ming", "BookTitle": "Chapu", "ChapterTitle": "Method of making scented tea by fumigation", "TokenCount": 71},
    {"Dynasty": "Ming", "BookTitle": "Chapu", "ChapterTitle": "Tea stove", "TokenCount": 98},
    {"Dynasty": "Ming", "BookTitle": "Chapu", "ChapterTitle": "Tea pet", "TokenCount": 165},
    {"Dynasty": "Ming", "BookTitle": "Chapu", "ChapterTitle": "Tea grinder", "TokenCount": 26},
    {"Dynasty": "Ming", "BookTitle": "Chapu", "ChapterTitle": "Tea roller", "TokenCount": 28},
    {"Dynasty": "Ming", "BookTitle": "Chapu", "ChapterTitle": "Tea sieve", "TokenCount": 22},
    {"Dynasty": "Ming", "BookTitle": "Chapu", "ChapterTitle": "Tea stand", "TokenCount": 31},
    {"Dynasty": "Ming", "BookTitle": "Chapu", "ChapterTitle": "Tea spoon", "TokenCount": 91},
    {"Dynasty": "Ming", "BookTitle": "Chapu", "ChapterTitle": "Tea whisk", "TokenCount": 43},
    {"Dynasty": "Ming", "BookTitle": "Chapu", "ChapterTitle": "Tea bowl", "TokenCount": 58},
    {"Dynasty": "Ming", "BookTitle": "Chapu", "ChapterTitle": "Tea bottle", "TokenCount": 92},
    {"Dynasty": "Ming", "BookTitle": "Chapu", "ChapterTitle": "Method of boiling soup for tea", "TokenCount": 59},
    {"Dynasty": "Ming", "BookTitle": "Chapu", "ChapterTitle": "Tasting water", "TokenCount": 309},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Producing tea", "TokenCount": 673},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Ancient and modern production methods", "TokenCount": 147},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Picking", "TokenCount": 252},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Frying tea", "TokenCount": 315},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Production method in Jiezhong", "TokenCount": 122},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Collecting", "TokenCount": 95},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Storing", "TokenCount": 277},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Taking", "TokenCount": 132},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Wrapping", "TokenCount": 62},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Daily storage and use", "TokenCount": 74},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Selecting water", "TokenCount": 319},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Storing water", "TokenCount": 114},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Scooping water", "TokenCount": 34},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Water boiling device", "TokenCount": 83},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Heat control", "TokenCount": 89},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Cooking and brewing", "TokenCount": 154},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Weighing", "TokenCount": 63},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Condition of the soup", "TokenCount": 69},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Pouring into the cup", "TokenCount": 357},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Washing", "TokenCount": 136},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Drinking and sipping", "TokenCount": 162},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Guests discussing", "TokenCount": 127},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Tea place", "TokenCount": 160},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Washing tea", "TokenCount": 150},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Boy servant", "TokenCount": 175},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Traveling", "TokenCount": 125},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Expediency", "TokenCount": 135},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Hulin water", "TokenCount": 119},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Appropriate moderation", "TokenCount": 138},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Debating", "TokenCount": 110},
    {"Dynasty": "Ming", "BookTitle": "Chashu", "ChapterTitle": "Investigating the origin", "TokenCount": 159},
    {"Dynasty": "Ming", "BookTitle": "Chaliaoji", "ChapterTitle": "Solitary Tasting", "TokenCount": 39},
    {"Dynasty": "Ming", "BookTitle": "Chaliaoji", "ChapterTitle": "Evaluating Spring", "TokenCount": 46},
    {"Dynasty": "Ming", "BookTitle": "Chaliaoji", "ChapterTitle": "Brewing Technique", "TokenCount": 79},
    {"Dynasty": "Ming", "BookTitle": "Chaliaoji", "ChapterTitle": "Tea Appreciation", "TokenCount": 33},
    {"Dynasty": "Ming", "BookTitle": "Chaliaoji", "ChapterTitle": "Optimal Tea Moment", "TokenCount": 30},
    {"Dynasty": "Ming", "BookTitle": "Chaliaoji", "ChapterTitle": "Tea Companion", "TokenCount": 26},
    {"Dynasty": "Ming", "BookTitle": "Chaliaoji", "ChapterTitle": "Tea's Meritorious Effects", "TokenCount": 27},
    {"Dynasty": "Ming", "BookTitle": "Zhuquanxiaopin", "ChapterTitle": "Source Spring", "TokenCount": 334},
    {"Dynasty": "Ming", "BookTitle": "Zhuquanxiaopin", "ChapterTitle": "Stone-filtered Stream", "TokenCount": 483},
    {"Dynasty": "Ming", "BookTitle": "Zhuquanxiaopin", "ChapterTitle": "Crystalline Chill", "TokenCount": 353},
    {"Dynasty": "Ming", "BookTitle": "Zhuquanxiaopin", "ChapterTitle": "Sweet Smell", "TokenCount": 341},
    {"Dynasty": "Ming", "BookTitle": "Zhuquanxiaopin", "ChapterTitle": "Tea-optimal Water", "TokenCount": 1594},
    {"Dynasty": "Ming", "BookTitle": "Zhuquanxiaopin", "ChapterTitle": "Divine Water", "TokenCount": 511},
    {"Dynasty": "Ming", "BookTitle": "Zhuquanxiaopin", "ChapterTitle": "Exceptional Springs", "TokenCount": 354},
    {"Dynasty": "Ming", "BookTitle": "Zhuquanxiaopin", "ChapterTitle": "River Waters", "TokenCount": 237},
    {"Dynasty": "Ming", "BookTitle": "Zhuquanxiaopin", "ChapterTitle": "Well Waters", "TokenCount": 287},
    {"Dynasty": "Ming", "BookTitle": "Zhuquanxiaopin", "ChapterTitle": "Epilogue on Waters", "TokenCount": 866},
])

# Define a color palette that matches the image you shared
colors = {
    'Chajing': '#1f77b4',         # blue
    'Shiliupintang': '#7f7f7f',   # gray
    'Daguanchalun': '#8c564b',    # brown
    'Chalu': '#2ca02c',           # green
    'Pinchayaolu': '#d62728',     # pink/red
    'Chapu': '#ff7f0e',           # orange
    'Chashu': '#9467bd',          # purple
    'Chaliaoji': '#e377c2',       # light pink
    'Zhuquanxiaopin': '#bcbd22'   # yellowish green
}

# Set a specific order for the dynasties (chronological)
dynasty_order = ['Tang', 'Song', 'Ming']

def create_dynasty_book_tokens_chart():
    # 将朝代转换为有序分类变量，确保正确的排序
    data['Dynasty'] = pd.Categorical(data['Dynasty'], categories=dynasty_order, ordered=True)

    # 使用 groupby 先汇总数据，再进行透视
    grouped_data = data.groupby(['Dynasty', 'BookTitle'])['TokenCount'].sum().reset_index()

    # 确保分组数据也使用相同的分类变量
    grouped_data['Dynasty'] = pd.Categorical(grouped_data['Dynasty'], categories=dynasty_order, ordered=True)

    # 按朝代顺序排序
    grouped_data = grouped_data.sort_values('Dynasty')

    # 然后创建透视表
    growth_df = grouped_data.pivot(index='Dynasty', columns='BookTitle', values='TokenCount')

    # 设置通用字体，避免找不到的问题
    plt.rcParams['font.family'] = 'sans-serif'
    plt.rcParams['font.size'] = 12

    # 创建图表
    fig, ax = plt.subplots(figsize=(16, 8))

    # 绘制堆叠条形图，并使用自定义颜色
    growth_df.plot.barh(stacked=True, ax=ax, width=0.7, color=[colors.get(col, '#333333') for col in growth_df.columns])

    # 添加标签和标题
    ax.set_xlabel('Number of tokens', fontweight='bold', fontsize=14)
    ax.set_ylabel('Dynasty', fontweight='bold', fontsize=14)
    ax.set_title('Total Token Distribution by Tea Books in Tang-Song-Ming Dynasties',
                fontweight='bold', fontsize=18)

    # 调整图例位置到图的外部右侧，避免与条形图重叠
    ax.legend(title='Book Title',
             loc='upper left',
             bbox_to_anchor=(1.01, 1.0),
             fontsize=11,
             title_fontsize=13)

    # 调整布局，给图例留出足够空间
    plt.tight_layout(rect=[0, 0, 0.85, 1])

    # 美化网格线
    ax.grid(axis='x', linestyle='--', alpha=0.7)
    ax.set_axisbelow(True)

    # 调整x轴刻度的间距
    ax.xaxis.set_major_locator(MaxNLocator(10))

    # 添加数据标签到每个部分
    for i, dynasty in enumerate(growth_df.index):
        xpos = 0
        for col in growth_df.columns:
            if pd.notna(growth_df.loc[dynasty, col]) and growth_df.loc[dynasty, col] > 0:
                value = growth_df.loc[dynasty, col]
                # 只给宽度足够的部分添加标签
                if value > 500:  # 只给宽度大于500的部分添加标签，避免拥挤
                    ax.text(xpos + value/2, i, f'{int(value)}',
                           ha='center', va='center', fontweight='bold', color='white')
                xpos += value

    # 显示图表
    plt.show()

    # 尝试保存到/tmp目录（如果需要的话）
    try:
        plt.savefig('/tmp/tea_books_tokens_per_dynasty.png', dpi=300, bbox_inches='tight')
        print("图表已保存到 /tmp/tea_books_tokens_per_dynasty.png")
    except Exception as e:
        print(f"保存图表时出错: {e}")

    return fig

# 执行函数并显示图表
fig = create_dynasty_book_tokens_chart()