# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u0lPrrePr62Fa2ycsUymUiiY-XRY_hgm
"""

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# 数据输入
data = {
    "Topics": ["Production", "Equipment", "Properties", "Water", "Ceremony", "Storage", "Other"],
    "Tang Dynasty": [364 + 381 + 218, 615 + 1847, 287, 0, 813, 0, 2805],
    "Song Dynasty": [120 + 91 + 96 + 105, 108 + 102 + 69 + 86 + 43 + 33, 122 + 66 + 102, 130 + 228 + 284, 473, 0, 77],
    "Ming Dynasty": [673 + 252 + 315, 157 + 91 + 98 + 92 + 165, 138 + 127 + 136,
                     319 + 114 + 1594 + 511 + 354 + 287 + 866, 150 + 309, 277, 175]
}

# 将数据加载为 Pandas DataFrame
df = pd.DataFrame(data)

# 设置图表大小
plt.figure(figsize=(14, 8))

# 创建柱状图
x = np.arange(len(df["Topics"]))  # x轴位置
width = 0.25  # 柱宽

# 配色
colors = ["#c1dd79", "#f5d0e2", "#d7d7d7"]

# 绘制每个朝代的柱状图
plt.bar(x - width, df["Tang Dynasty"], width, label="Tang Dynasty", color=colors[0])  # 黄色
plt.bar(x, df["Song Dynasty"], width, label="Song Dynasty", color=colors[1])          # 绿色
plt.bar(x + width, df["Ming Dynasty"], width, label="Ming Dynasty", color=colors[2])  # 蓝色

# 设置x轴标签
plt.xticks(x, df["Topics"], rotation=45, ha="right", fontsize=12)
plt.xlabel("Topics", fontsize=14,)
plt.ylabel("Token Count", fontsize=14, )


# 添加图例
plt.legend(title="Dynasties", fontsize=12, title_fontsize=14)

# 添加网格线
plt.grid(axis="y", linestyle="--", alpha=0.7)

# 调整布局
plt.tight_layout()

# 显示图表
plt.show()