# -*- coding: utf-8 -*-
"""Thematic_Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186cz5sTkRea1I4QbAKlCSKG1HrcS-jpx
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

# 创建茶书章节主题数据
tea_data = pd.DataFrame([
    # 生产相关章节
    {"ChapterTitle": "The Origin of Tea", "Topic": "Production", "TokenCount": 364, "Dynasty": "Tang", "BookTitle": "Chajing"},
    {"ChapterTitle": "The Manufacturing of Tea", "Topic": "Production", "TokenCount": 381, "Dynasty": "Tang", "BookTitle": "Chajing"},
    {"ChapterTitle": "Producing tea", "Topic": "Production", "TokenCount": 673, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Ancient and modern production methods", "Topic": "Production", "TokenCount": 147, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Picking", "Topic": "Production", "TokenCount": 252, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Frying tea", "Topic": "Production", "TokenCount": 315, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Production method in Jiezhong", "Topic": "Production", "TokenCount": 122, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Making powdered tea", "Topic": "Production", "TokenCount": 127, "Dynasty": "Ming", "BookTitle": "Chapu"},
    {"ChapterTitle": "Method of making scented tea by fumigation", "Topic": "Production", "TokenCount": 71, "Dynasty": "Ming", "BookTitle": "Chapu"},
    {"ChapterTitle": "Timing", "Topic": "Production", "TokenCount": 108, "Dynasty": "Song", "BookTitle": "Daguanchalun"},
    {"ChapterTitle": "Selection and picking", "Topic": "Production", "TokenCount": 120, "Dynasty": "Song", "BookTitle": "Daguanchalun"},
    {"ChapterTitle": "Steaming and pressing", "Topic": "Production", "TokenCount": 91, "Dynasty": "Song", "BookTitle": "Daguanchalun"},
    {"ChapterTitle": "Manufacturing", "Topic": "Production", "TokenCount": 96, "Dynasty": "Song", "BookTitle": "Daguanchalun"},
    {"ChapterTitle": "Grinding with a sieve", "Topic": "Production", "TokenCount": 151, "Dynasty": "Song", "BookTitle": "Daguanchalun"},
    {"ChapterTitle": "White tea", "Topic": "Production", "TokenCount": 133, "Dynasty": "Song", "BookTitle": "Daguanchalun"},
    {"ChapterTitle": "Picking and manufacturing at an improper time", "Topic": "Production", "TokenCount": 188, "Dynasty": "Song", "BookTitle": "Pinchayaolu"},

    # 器具相关章节
    {"ChapterTitle": "The Tools for Tea Production", "Topic": "Equipment", "TokenCount": 615, "Dynasty": "Tang", "BookTitle": "Chajing"},
    {"ChapterTitle": "The Utensils for Tea", "Topic": "Equipment", "TokenCount": 1847, "Dynasty": "Tang", "BookTitle": "Chajing"},
    {"ChapterTitle": "Tea stove", "Topic": "Equipment", "TokenCount": 98, "Dynasty": "Ming", "BookTitle": "Chapu"},
    {"ChapterTitle": "Tea pet", "Topic": "Equipment", "TokenCount": 165, "Dynasty": "Ming", "BookTitle": "Chapu"},
    {"ChapterTitle": "Tea grinder", "Topic": "Equipment", "TokenCount": 26, "Dynasty": "Ming", "BookTitle": "Chapu"},
    {"ChapterTitle": "Tea roller", "Topic": "Equipment", "TokenCount": 28, "Dynasty": "Ming", "BookTitle": "Chapu"},
    {"ChapterTitle": "Tea sieve", "Topic": "Equipment", "TokenCount": 22, "Dynasty": "Ming", "BookTitle": "Chapu"},
    {"ChapterTitle": "Tea stand", "Topic": "Equipment", "TokenCount": 31, "Dynasty": "Ming", "BookTitle": "Chapu"},
    {"ChapterTitle": "Tea spoon", "Topic": "Equipment", "TokenCount": 91, "Dynasty": "Ming", "BookTitle": "Chapu"},
    {"ChapterTitle": "Tea whisk", "Topic": "Equipment", "TokenCount": 43, "Dynasty": "Ming", "BookTitle": "Chapu"},
    {"ChapterTitle": "Tea bowl", "Topic": "Equipment", "TokenCount": 58, "Dynasty": "Ming", "BookTitle": "Chapu"},
    {"ChapterTitle": "Tea bottle", "Topic": "Equipment", "TokenCount": 92, "Dynasty": "Ming", "BookTitle": "Chapu"},
    {"ChapterTitle": "Water boiling device", "Topic": "Equipment", "TokenCount": 83, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Tea bowl", "Topic": "Equipment", "TokenCount": 102, "Dynasty": "Song", "BookTitle": "Daguanchalun"},
    {"ChapterTitle": "Tea whisk", "Topic": "Equipment", "TokenCount": 69, "Dynasty": "Song", "BookTitle": "Daguanchalun"},
    {"ChapterTitle": "Bottle", "Topic": "Equipment", "TokenCount": 86, "Dynasty": "Song", "BookTitle": "Daguanchalun"},
    {"ChapterTitle": "Spoon", "Topic": "Equipment", "TokenCount": 43, "Dynasty": "Song", "BookTitle": "Daguanchalun"},
    {"ChapterTitle": "Tea roasting oven", "Topic": "Equipment", "TokenCount": 55, "Dynasty": "Song", "BookTitle": "Chalu"},
    {"ChapterTitle": "Tea basket", "Topic": "Equipment", "TokenCount": 27, "Dynasty": "Song", "BookTitle": "Chalu"},
    {"ChapterTitle": "Anvil and mallet", "Topic": "Equipment", "TokenCount": 25, "Dynasty": "Song", "BookTitle": "Chalu"},
    {"ChapterTitle": "Tea lock", "Topic": "Equipment", "TokenCount": 14, "Dynasty": "Song", "BookTitle": "Chalu"},
    {"ChapterTitle": "Tea mill", "Topic": "Equipment", "TokenCount": 28, "Dynasty": "Song", "BookTitle": "Chalu"},
    {"ChapterTitle": "Tea sieve", "Topic": "Equipment", "TokenCount": 30, "Dynasty": "Song", "BookTitle": "Chalu"},
    {"ChapterTitle": "Tea bowl", "Topic": "Equipment", "TokenCount": 68, "Dynasty": "Song", "BookTitle": "Chalu"},
    {"ChapterTitle": "Tea spoon", "Topic": "Equipment", "TokenCount": 33, "Dynasty": "Song", "BookTitle": "Chalu"},
    {"ChapterTitle": "Hot water bottle", "Topic": "Equipment", "TokenCount": 36, "Dynasty": "Song", "BookTitle": "Chalu"},

    # 茶叶特性相关章节
    {"ChapterTitle": "The Essentials of Tea", "Topic": "Properties", "TokenCount": 287, "Dynasty": "Tang", "BookTitle": "Chajing"},
    {"ChapterTitle": "Taste", "Topic": "Properties", "TokenCount": 122, "Dynasty": "Song", "BookTitle": "Daguanchalun"},
    {"ChapterTitle": "Smell", "Topic": "Properties", "TokenCount": 66, "Dynasty": "Song", "BookTitle": "Daguanchalun"},
    {"ChapterTitle": "Color", "Topic": "Properties", "TokenCount": 102, "Dynasty": "Song", "BookTitle": "Daguanchalun"},
    {"ChapterTitle": "Color", "Topic": "Properties", "TokenCount": 91, "Dynasty": "Song", "BookTitle": "Chalu"},
    {"ChapterTitle": "Smell", "Topic": "Properties", "TokenCount": 61, "Dynasty": "Song", "BookTitle": "Chalu"},
    {"ChapterTitle": "Taste", "Topic": "Properties", "TokenCount": 69, "Dynasty": "Song", "BookTitle": "Chalu"},
    {"ChapterTitle": "Condition of the soup", "Topic": "Properties", "TokenCount": 69, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Appraisal and discrimination", "Topic": "Properties", "TokenCount": 230, "Dynasty": "Song", "BookTitle": "Daguanchalun"},
    {"ChapterTitle": "Appropriate moderation", "Topic": "Properties", "TokenCount": 138, "Dynasty": "Ming", "BookTitle": "Chashu"},

    # 水源相关章节
    {"ChapterTitle": "Water", "Topic": "Water", "TokenCount": 130, "Dynasty": "Song", "BookTitle": "Daguanchalun"},
    {"ChapterTitle": "Selecting water", "Topic": "Water", "TokenCount": 319, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Storing water", "Topic": "Water", "TokenCount": 114, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Scooping water", "Topic": "Water", "TokenCount": 34, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Tasting water", "Topic": "Water", "TokenCount": 309, "Dynasty": "Ming", "BookTitle": "Chapu"},
    {"ChapterTitle": "Hulin water", "Topic": "Water", "TokenCount": 119, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Source Spring", "Topic": "Water", "TokenCount": 334, "Dynasty": "Ming", "BookTitle": "Zhuquanxiaopin"},
    {"ChapterTitle": "Stone-filtered Stream", "Topic": "Water", "TokenCount": 483, "Dynasty": "Ming", "BookTitle": "Zhuquanxiaopin"},
    {"ChapterTitle": "Crystalline Chill", "Topic": "Water", "TokenCount": 353, "Dynasty": "Ming", "BookTitle": "Zhuquanxiaopin"},
    {"ChapterTitle": "Sweet Smell", "Topic": "Water", "TokenCount": 341, "Dynasty": "Ming", "BookTitle": "Zhuquanxiaopin"},
    {"ChapterTitle": "Tea-optimal Water", "Topic": "Water", "TokenCount": 1594, "Dynasty": "Ming", "BookTitle": "Zhuquanxiaopin"},
    {"ChapterTitle": "Divine Water", "Topic": "Water", "TokenCount": 511, "Dynasty": "Ming", "BookTitle": "Zhuquanxiaopin"},
    {"ChapterTitle": "Exceptional Springs", "Topic": "Water", "TokenCount": 354, "Dynasty": "Ming", "BookTitle": "Zhuquanxiaopin"},
    {"ChapterTitle": "River Waters", "Topic": "Water", "TokenCount": 237, "Dynasty": "Ming", "BookTitle": "Zhuquanxiaopin"},
    {"ChapterTitle": "Well Waters", "Topic": "Water", "TokenCount": 287, "Dynasty": "Ming", "BookTitle": "Zhuquanxiaopin"},
    {"ChapterTitle": "Epilogue on Waters", "Topic": "Water", "TokenCount": 866, "Dynasty": "Ming", "BookTitle": "Zhuquanxiaopin"},
    {"ChapterTitle": "Distinguishing the sources of the gully and the Shaxi River", "Topic": "Water", "TokenCount": 331, "Dynasty": "Song", "BookTitle": "Pinchayaolu"},

    # 仪式相关章节
    {"ChapterTitle": "The Brewing of Tea", "Topic": "Ceremony", "TokenCount": 813, "Dynasty": "Tang", "BookTitle": "Chajing"},
    {"ChapterTitle": "The Drinking of Tea", "Topic": "Ceremony", "TokenCount": 481, "Dynasty": "Tang", "BookTitle": "Chajing"},
    {"ChapterTitle": "Infusion", "Topic": "Ceremony", "TokenCount": 473, "Dynasty": "Song", "BookTitle": "Daguanchalun"},
    {"ChapterTitle": "Waiting for the water to boil", "Topic": "Ceremony", "TokenCount": 49, "Dynasty": "Song", "BookTitle": "Chalu"},
    {"ChapterTitle": "Heating the tea bowl", "Topic": "Ceremony", "TokenCount": 18, "Dynasty": "Song", "BookTitle": "Chalu"},
    {"ChapterTitle": "Making powdered tea", "Topic": "Ceremony", "TokenCount": 105, "Dynasty": "Song", "BookTitle": "Chalu"},
    {"ChapterTitle": "Method of boiling soup for tea", "Topic": "Ceremony", "TokenCount": 59, "Dynasty": "Ming", "BookTitle": "Chapu"},
    {"ChapterTitle": "Heat control", "Topic": "Ceremony", "TokenCount": 89, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Cooking and brewing", "Topic": "Ceremony", "TokenCount": 154, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Weighing", "Topic": "Ceremony", "TokenCount": 63, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Pouring into the cup", "Topic": "Ceremony", "TokenCount": 357, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Washing", "Topic": "Ceremony", "TokenCount": 136, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Drinking and sipping", "Topic": "Ceremony", "TokenCount": 162, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Guests discussing", "Topic": "Ceremony", "TokenCount": 127, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Tea place", "Topic": "Ceremony", "TokenCount": 160, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Washing tea", "Topic": "Ceremony", "TokenCount": 150, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Boy servant", "Topic": "Ceremony", "TokenCount": 175, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Tasting tea", "Topic": "Ceremony", "TokenCount": 99, "Dynasty": "Ming", "BookTitle": "Chapu"},
    {"ChapterTitle": "Brewing Technique", "Topic": "Ceremony", "TokenCount": 79, "Dynasty": "Ming", "BookTitle": "Chaliaoji"},
    {"ChapterTitle": "Tea Appreciation", "Topic": "Ceremony", "TokenCount": 33, "Dynasty": "Ming", "BookTitle": "Chaliaoji"},
    {"ChapterTitle": "Optimal Tea Moment", "Topic": "Ceremony", "TokenCount": 30, "Dynasty": "Ming", "BookTitle": "Chaliaoji"},
    {"ChapterTitle": "Pouring into the cup", "Topic": "Ceremony", "TokenCount": 357, "Dynasty": "Ming", "BookTitle": "Chashu"},

    # 储存相关章节
    {"ChapterTitle": "Storage and roasting", "Topic": "Storage", "TokenCount": 228, "Dynasty": "Song", "BookTitle": "Daguanchalun"},
    {"ChapterTitle": "External roasting", "Topic": "Storage", "TokenCount": 284, "Dynasty": "Song", "BookTitle": "Daguanchalun"},
    {"ChapterTitle": "Stored tea", "Topic": "Storage", "TokenCount": 63, "Dynasty": "Song", "BookTitle": "Chalu"},
    {"ChapterTitle": "Roasted tea", "Topic": "Storage", "TokenCount": 61, "Dynasty": "Song", "BookTitle": "Chalu"},
    {"ChapterTitle": "Milled tea", "Topic": "Storage", "TokenCount": 37, "Dynasty": "Song", "BookTitle": "Chalu"},
    {"ChapterTitle": "Sieved tea", "Topic": "Storage", "TokenCount": 11, "Dynasty": "Song", "BookTitle": "Chalu"},
    {"ChapterTitle": "Collecting", "Topic": "Storage", "TokenCount": 95, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Storing", "Topic": "Storage", "TokenCount": 277, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Taking", "Topic": "Storage", "TokenCount": 132, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Wrapping", "Topic": "Storage", "TokenCount": 62, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Daily storage and use", "Topic": "Storage", "TokenCount": 74, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Collecting tea", "Topic": "Storage", "TokenCount": 157, "Dynasty": "Ming", "BookTitle": "Chapu"},

    # 其他章节
    {"ChapterTitle": "The Stories about Tea", "Topic": "Other", "TokenCount": 2805, "Dynasty": "Tang", "BookTitle": "Chajing"},
    {"ChapterTitle": "The Origins of Tea Producing Areas", "Topic": "Other", "TokenCount": 218, "Dynasty": "Tang", "BookTitle": "Chajing"},
    {"ChapterTitle": "Product name", "Topic": "Other", "TokenCount": 190, "Dynasty": "Song", "BookTitle": "Daguanchalun"},
    {"ChapterTitle": "Real estate", "Topic": "Other", "TokenCount": 77, "Dynasty": "Song", "BookTitle": "Daguanchalun"},
    {"ChapterTitle": "General Introduction", "Topic": "Other", "TokenCount": 316, "Dynasty": "Song", "BookTitle": "Pinchayaolu"},
    {"ChapterTitle": "Post-discussion", "Topic": "Other", "TokenCount": 294, "Dynasty": "Song", "BookTitle": "Pinchayaolu"},
    {"ChapterTitle": "Traveling", "Topic": "Other", "TokenCount": 125, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Expediency", "Topic": "Other", "TokenCount": 135, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Debating", "Topic": "Other", "TokenCount": 110, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Investigating the origin", "Topic": "Other", "TokenCount": 159, "Dynasty": "Ming", "BookTitle": "Chashu"},
    {"ChapterTitle": "Solitary Tasting", "Topic": "Other", "TokenCount": 39, "Dynasty": "Ming", "BookTitle": "Chaliaoji"},
    {"ChapterTitle": "Evaluating Spring", "Topic": "Other", "TokenCount": 46, "Dynasty": "Ming", "BookTitle": "Chaliaoji"},
    {"ChapterTitle": "Tea Companion", "Topic": "Other", "TokenCount": 26, "Dynasty": "Ming", "BookTitle": "Chaliaoji"},
    {"ChapterTitle": "Tea's Meritorious Effects", "Topic": "Other", "TokenCount": 27, "Dynasty": "Ming", "BookTitle": "Chaliaoji"},

    # 其他特殊内容
    {"ChapterTitle": "Mixing in white lotuses and stolen leaves", "Topic": "Other", "TokenCount": 189, "Dynasty": "Song", "BookTitle": "Pinchayaolu"},
    {"ChapterTitle": "Adding impurities", "Topic": "Other", "TokenCount": 139, "Dynasty": "Song", "BookTitle": "Pinchayaolu"},
    {"ChapterTitle": "Insufficient steaming", "Topic": "Other", "TokenCount": 89, "Dynasty": "Song", "BookTitle": "Pinchayaolu"},
    {"ChapterTitle": "Over-steaming", "Topic": "Other", "TokenCount": 77, "Dynasty": "Song", "BookTitle": "Pinchayaolu"},
    {"ChapterTitle": "Burnt pot", "Topic": "Other", "TokenCount": 63, "Dynasty": "Song", "BookTitle": "Pinchayaolu"},
    {"ChapterTitle": "Pressed yellow", "Topic": "Other", "TokenCount": 129, "Dynasty": "Song", "BookTitle": "Pinchayaolu"},
    {"ChapterTitle": "Soaked paste", "Topic": "Other", "TokenCount": 70, "Dynasty": "Song", "BookTitle": "Pinchayaolu"},
    {"ChapterTitle": "Damaged roasting", "Topic": "Other", "TokenCount": 115, "Dynasty": "Song", "BookTitle": "Pinchayaolu"}
])

# 定义主题的颜色映射，使用柔和的颜色，类似于示例图
topic_colors = {
    'Production': '#5b9bd5',  # 蓝色
    'Equipment': '#ed7d31',   # 橙色
    'Properties': '#a5a5a5',  # 灰色
    'Water': '#ffc000',       # 黄色
    'Ceremony': '#70ad47',    # 绿色
    'Storage': '#4472c4',     # 深蓝色
    'Other': '#c55a11'        # 棕色
}

# 定义线型样式，类似于示例图
topic_linestyles = {
    'Production': '-',      # 实线
    'Equipment': '--',     # 短划线
    'Properties': '-.',    # 点划线
    'Water': ':',         # 点线
    'Ceremony': '-',      # 实线
    'Storage': '--',      # 短划线
    'Other': '-.'         # 点划线
}

# 线宽度
topic_linewidths = {
    'Production': 2.0,
    'Equipment': 1.8,
    'Properties': 1.8,
    'Water': 1.8,
    'Ceremony': 1.8,
    'Storage': 1.8,
    'Other': 1.8
}

# 标记样式
topic_markers = {
    'Production': 'o',
    'Equipment': 's',
    'Properties': '^',
    'Water': 'D',
    'Ceremony': 'v',
    'Storage': 'p',
    'Other': 'X'
}

def create_line_trend_plot(data):
    # 设置字体和样式
    plt.rcParams['font.family'] = 'sans-serif'
    plt.rcParams['font.sans-serif'] = ['Arial', 'DejaVu Sans', 'Liberation Sans']
    plt.rcParams['font.size'] = 10

    # 创建图表
    plt.figure(figsize=(12, 8), facecolor='white')

    # 设置朝代顺序
    dynasty_order = ['Tang', 'Song', 'Ming']

    # 计算每个朝代和主题下的章节数量
    # 这里用两种方式：章节数量和总字数
    # 1. 统计章节数量
    topic_counts = data.groupby(['Dynasty', 'Topic']).size().unstack(fill_value=0)
    topic_counts = topic_counts.reindex(dynasty_order)

    # 2. 统计总字数
    topic_tokens = data.groupby(['Dynasty', 'Topic'])['TokenCount'].sum().unstack(fill_value=0)
    topic_tokens = topic_tokens.reindex(dynasty_order)

    # 使用第二种方式（总字数）来绘制线图
    topics = data['Topic'].unique()

    # 绘制网格线
    plt.grid(True, linestyle='--', alpha=0.7, color='#e0e0e0')

    # 绘制每个主题的线
    for topic in topics:
        if topic in topic_tokens.columns:
            plt.plot(
                topic_tokens.index,
                topic_tokens[topic],
                label=topic,
                color=topic_colors.get(topic, 'gray'),
                linestyle=topic_linestyles.get(topic, '-'),
                linewidth=topic_linewidths.get(topic, 2),
                marker=topic_markers.get(topic, 'o'),
                markersize=8,
                alpha=0.8
            )

    # 设置x轴刻度和标签
    plt.xticks(range(len(dynasty_order)), dynasty_order, fontsize=11)

    # 设置标题和轴标签
    plt.title('Thematic Clustering of Tea Book Chapters in Tang, Song, and Ming Dynasties', fontsize=16, fontweight='bold', pad=20)
    plt.xlabel('Dynasty', fontsize=12, labelpad=10)
    plt.ylabel('Total Word Count', fontsize=12, labelpad=10)

    # 创建图例，放在图表右侧
    plt.legend(
        title='Topics',
        loc='center left',
        bbox_to_anchor=(1.02, 0.5),
        frameon=True,
        fontsize=10,
        title_fontsize=12
    )

    # 调整布局，确保所有内容可见
    plt.tight_layout(rect=[0, 0, 0.85, 1])

    return plt.gcf()

# 创建并显示线图
trend_fig = create_line_trend_plot(tea_data)
plt.savefig('tea_topics_dynasty_trend.png', dpi=300, bbox_inches='tight')
plt.show()