# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152c9hvMgxeD_XXpLOX_TIuu9tyD2SuHU
"""

import plotly.graph_objects as go

# 数据矩阵
z = [
    [145, 7, 15, 12, 3],    # Visual
    [7, 30, 15, 4, 0],      # Taste
    [15, 15, 64, 2, 0],     # Smell
    [12, 4, 2, 25, 1],      # Touch
    [3, 0, 0, 1, 11]        # Hearing
]

# 标签（保持中英文均可，这里保持英文）
senses = ['Visual', 'Taste', 'Smell', 'Touch', 'Hearing']

# 自定义颜色方案
colorscale = [
    [0, '#070720'],
    [0.1, '#0c0b2a'],
    [0.2, '#191345'],
    [0.3, '#2f1657'],
    [0.4, '#3f1d55'],
    [0.5, '#68255a'],
    [0.6, '#a12b52'],
    [0.7, '#d8413c'],
    [0.8, '#f5784f'],
    [0.9, '#faaf8c'],
    [1.0, '#faecd4']
]

# 创建热力图
fig = go.Figure(data=go.Heatmap(
    z=z,
    x=senses,
    y=senses,
    colorscale=colorscale,
    zmin=0,
    zmax=145,
    text=z,  # 添加文本数据
    texttemplate="%{text}",  # 文本显示格式
    textfont={"size":14, "color":"white"},  # 文本样式
    hoverinfo="text",
    colorbar=dict(
        title='',
        thickness=20,
        tickfont=dict(size=12),
        outlinewidth=0
    )
))

# 更新布局
fig.update_layout(
    title={
        'text': "五感词汇共现次数",
        'font': {'size': 20}
    },
    xaxis=dict(
        title='',
        tickangle=0,
        tickfont=dict(size=14),
        showline=False,
        mirror=False
    ),
    yaxis=dict(
        title='',
        tickfont=dict(size=14),
        showline=False,
        mirror=False
    ),
    margin=dict(l=70, r=50, b=70, t=80, pad=0),
    plot_bgcolor='white',
    paper_bgcolor='white',
    width=800,
    height=700
)

# 显示图表
fig.show()