# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ew4jl47PKVPWu-BbJNLN-Tn4aQFi9SEX
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import jieba
import re
from wordcloud import WordCloud
import matplotlib.font_manager as fm
from collections import Counter
import os

# 设置中文字体
plt.rcParams['font.sans-serif'] = ['SimHei']  # 用来正常显示中文标签
plt.rcParams['axes.unicode_minus'] = False  # 用来正常显示负号

# 读取Excel文件
df = pd.read_excel('/home/ubuntu/upload/tokenized_results_20250407_175131.xlsx')

# 检查并删除第一行（如果它是错误的标题行）
if '﻿原文,visual,taste,smell,touch,sound' in str(df.iloc[0]['原文']):
    df = df.iloc[1:].reset_index(drop=True)

# 定义五感词汇列名
sense_columns = ['visual词', 'taste词', 'smell词', 'touch词', 'sound词']
sense_count_columns = ['视觉词数', '味觉词数', '嗅觉词数', '触觉词数', '听觉词数']

# 清理文本函数
def clean_text(text):
    if not isinstance(text, str):
        return ""

    # 删除重复的逗号
    text = re.sub(r',+', ',', text)

    # 删除开头和结尾的逗号
    text = text.strip(',')

    # 删除重复的中文文字
    # 这里使用简单的方法，检测连续相同的字符
    text = re.sub(r'(.)\1+', r'\1', text)

    return text

# 检查句子是否包含五感词汇
def has_sense_words(row):
    for col in sense_columns:
        if isinstance(row[col], str) and row[col].strip() and row[col] != ',':
            return True

    # 检查五感词数是否大于0
    for col in sense_count_columns:
        if row[col] > 0:
            return True

    return False

# 清理数据
df['原文'] = df['原文'].apply(clean_text)
df['分词结果'] = df['分词结果'].apply(clean_text)

for col in sense_columns:
    df[col] = df[col].apply(clean_text)

# 只保留包含五感词汇的句子
df_cleaned = df[df.apply(has_sense_words, axis=1)].copy()

# 保存清理后的数据
df_cleaned.to_excel('/home/ubuntu/five_senses_analysis/cleaned_data.xlsx', index=False)

# 分析清理后的内容
total_rows = len(df_cleaned)
print(f"清理后的总行数: {total_rows}")

# 统计每种感官词汇的总数和平均数
sense_stats = {}
for col, count_col in zip(sense_columns, sense_count_columns):
    sense_name = col.replace('词', '')
    total = df_cleaned[count_col].sum()
    avg = total / total_rows if total_rows > 0 else 0
    sense_stats[sense_name] = {'总数': total, '平均数': avg}

# 创建统计结果DataFrame
stats_df = pd.DataFrame(sense_stats).T
stats_df.to_csv('/home/ubuntu/five_senses_analysis/sense_stats.csv')

# 提取所有五感词汇
all_sense_words = {}
for col in sense_columns:
    sense_name = col.replace('词', '')
    words = []
    for word in df_cleaned[col]:
        if isinstance(word, str) and word.strip():
            words.extend([w for w in word.split(',') if w.strip()])
    all_sense_words[sense_name] = words

# 统计每种感官最常见的词汇
top_words = {}
for sense, words in all_sense_words.items():
    if words:
        word_counts = Counter(words)
        top_words[sense] = word_counts.most_common(10)

# 保存最常见词汇
with open('/home/ubuntu/five_senses_analysis/top_words.txt', 'w', encoding='utf-8') as f:
    for sense, words in top_words.items():
        f.write(f"{sense}最常见的10个词:\n")
        for word, count in words:
            f.write(f"{word}: {count}\n")
        f.write("\n")

# 创建可视化

# 1. 五感词汇数量分布
plt.figure(figsize=(12, 6))
sns.barplot(x=list(sense_stats.keys()), y=[stats['总数'] for stats in sense_stats.values()])
plt.title('五感词汇数量分布')
plt.xlabel('感官类型')
plt.ylabel('词汇总数')
plt.tight_layout()
plt.savefig('/home/ubuntu/five_senses_analysis/sense_distribution.png')

# 2. 每种感官词汇的词云图
for sense, words in all_sense_words.items():
    if words:
        text = ' '.join(words)
        wordcloud = WordCloud(width=800, height=400, background_color='white',
                             font_path='/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',
                             max_words=100).generate(text)

        plt.figure(figsize=(10, 5))
        plt.imshow(wordcloud, interpolation='bilinear')
        plt.axis('off')
        plt.title(f'{sense}词云图')
        plt.tight_layout()
        plt.savefig(f'/home/ubuntu/five_senses_analysis/{sense}_wordcloud.png')

# 3. 五感词汇在句子中的分布情况
sense_presence = {}
for col in sense_count_columns:
    sense_name = col.replace('词数', '')
    presence = (df_cleaned[col] > 0).sum()
    percentage = (presence / total_rows) * 100 if total_rows > 0 else 0
    sense_presence[sense_name] = percentage

plt.figure(figsize=(12, 6))
sns.barplot(x=list(sense_presence.keys()), y=list(sense_presence.values()))
plt.title('包含各类感官词汇的句子比例')
plt.xlabel('感官类型')
plt.ylabel('百分比 (%)')
plt.tight_layout()
plt.savefig('/home/ubuntu/five_senses_analysis/sense_presence_percentage.png')

# 4. 五感词汇共现分析
cooccurrence = np.zeros((5, 5))
sense_names = [col.replace('词数', '') for col in sense_count_columns]

for i, col1 in enumerate(sense_count_columns):
    for j, col2 in enumerate(sense_count_columns):
        if i <= j:  # 只计算上三角矩阵（包括对角线）
            cooccurrence[i, j] = ((df_cleaned[col1] > 0) & (df_cleaned[col2] > 0)).sum()
            if i != j:  # 对称矩阵
                cooccurrence[j, i] = cooccurrence[i, j]

plt.figure(figsize=(10, 8))
sns.heatmap(cooccurrence, annot=True, fmt='g', xticklabels=sense_names, yticklabels=sense_names)
plt.title('五感词汇共现次数')
plt.tight_layout()
plt.savefig('/home/ubuntu/five_senses_analysis/sense_cooccurrence.png')

# 生成分析报告
with open('/home/ubuntu/five_senses_analysis/analysis_report.md', 'w', encoding='utf-8') as f:
    f.write("# 五感词汇分析报告\n\n")

    f.write("## 数据清理结果\n")
    f.write(f"- 原始数据行数: {len(df)}\n")
    f.write(f"- 清理后数据行数: {total_rows}\n")
    f.write(f"- 删除的行数: {len(df) - total_rows}\n\n")

    f.write("## 五感词汇统计\n\n")
    f.write("| 感官类型 | 词汇总数 | 平均每句词数 |\n")
    f.write("|---------|----------|------------|\n")
    for sense, stats in sense_stats.items():
        f.write(f"| {sense} | {stats['总数']} | {stats['平均数']:.2f} |\n")
    f.write("\n")

    f.write("## 各感官最常见词汇\n\n")
    for sense, words in top_words.items():
        f.write(f"### {sense}最常见的词汇\n\n")
        f.write("| 词汇 | 出现次数 |\n")
        f.write("|------|----------|\n")
        for word, count in words:
            f.write(f"| {word} | {count} |\n")
        f.write("\n")

    f.write("## 五感词汇在句子中的分布\n\n")
    f.write("| 感官类型 | 包含该类词汇的句子比例 |\n")
    f.write("|---------|--------------------|\n")
    for sense, percentage in sense_presence.items():
        f.write(f"| {sense} | {percentage:.2f}% |\n")
    f.write("\n")

    f.write("## 结论\n\n")

    # 找出最常用的感官词汇类型
    most_common_sense = max(sense_stats.items(), key=lambda x: x[1]['总数'])
    f.write(f"- 在分析的文本中，{most_common_sense[0]}词汇使用最为频繁，总计{most_common_sense[1]['总数']}个词。\n")

    # 找出最少用的感官词汇类型
    least_common_sense = min(sense_stats.items(), key=lambda x: x[1]['总数'])
    f.write(f"- {least_common_sense[0]}词汇使用最少，仅有{least_common_sense[1]['总数']}个词。\n")

    # 计算五感词汇的总体分布
    total_sense_words = sum(stats['总数'] for stats in sense_stats.values())
    f.write("\n### 五感词汇分布比例\n\n")
    for sense, stats in sense_stats.items():
        percentage = (stats['总数'] / total_sense_words) * 100 if total_sense_words > 0 else 0
        f.write(f"- {sense}: {percentage:.2f}%\n")

    f.write("\n### 共现分析\n\n")
    # 找出最常共现的两种感官
    max_cooccurrence = 0
    max_pair = None
    for i in range(5):
        for j in range(i+1, 5):  # 只检查上三角矩阵（不包括对角线）
            if cooccurrence[i, j] > max_cooccurrence:
                max_cooccurrence = cooccurrence[i, j]
                max_pair = (sense_names[i], sense_names[j])

    if max_pair:
        f.write(f"- {max_pair[0]}和{max_pair[1]}词汇最常共同出现在同一句中，共出现{int(max_cooccurrence)}次。\n")

    f.write("\n## 可视化图表\n\n")
    f.write("1. 五感词汇数量分布\n")
    f.write("2. 各感官词云图\n")
    f.write("3. 包含各类感官词汇的句子比例\n")
    f.write("4. 五感词汇共现分析热力图\n")