# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_pu-_NLu0QbqaX8FnMDEpQlbVWDuPUMh
"""

import plotly.graph_objects as go
from plotly.subplots import make_subplots

# 配置数据
data = {
    'visual': {
        'labels': ['白', '碗', '玉', '绿', '黄', '青', '金', '红'],
        'values': [13, 9, 8, 7, 6, 5, 4, 4]
    },
    'smell': {
        'labels': ['香', '清', '芳', '烟', '茶香', '幽'],
        'values': [17, 10, 10, 7, 4, 4]
    },
    'taste': {
        'labels': ['清', '甘', '鲜', '茶味', '润', '薄'],
        'values': [11, 3, 3, 2, 2, 2]
    },
    'touch': {
        'labels': ['春风', '蒸', '凝', '研', '冷', '润'],
        'values': [5, 4, 4, 3, 3, 2]
    },
    'hearing': {
        'labels': ['碾声', '凿石', '潺', '泠', '凿', '潺湲声'],
        'values': [2, 1, 1, 1, 1, 1]
    }
}

# 颜色配置
colors = {
    'visual': 'rgba(121, 199, 183, 0.5)',    # 浅青绿色
    'smell': 'rgba(97, 142, 204, 0.5)',      # 蓝色
    'taste': 'rgba(241, 109, 122, 0.5)',     # 红色
    'touch': 'rgba(246, 185, 128, 0.5)',     # 橙色
    'hearing': 'rgba(188, 216, 105, 0.5)'    # 黄绿色
}

border_colors = {
    'visual': 'rgba(121, 199, 183, 1)',
    'smell': 'rgba(97, 142, 204, 1)',
    'taste': 'rgba(241, 109, 122, 1)',
    'touch': 'rgba(246, 185, 128, 1)',
    'hearing': 'rgba(188, 216, 105, 1)'
}

# 创建子图布局
fig = make_subplots(
    rows=2, cols=3,
    specs=[
        [{'type': 'polar'}, {'type': 'polar'}, {'type': 'polar'}],
        [{'type': 'polar'}, {'type': 'polar'}, {'type': 'polar'}]
    ],
    subplot_titles=("视觉", "嗅觉", "味觉", "触觉", "听觉"),
    vertical_spacing=0.15,
    horizontal_spacing=0.1
)

# 添加每个雷达图
senses = ['visual', 'smell', 'taste', 'touch', 'hearing']
positions = [(1,1), (1,2), (1,3), (2,1), (2,2)]

for idx, sense in enumerate(senses):
    row, col = positions[idx]

    fig.add_trace(
        go.Scatterpolar(
            r=data[sense]['values'] + [data[sense]['values'][0]],  # 闭合图形
            theta=data[sense]['labels'] + [data[sense]['labels'][0]],
            fill='toself',
            fillcolor=colors[sense],
            line=dict(color=border_colors[sense], width=2),
            hoverinfo='text',
            text=[f'Count: {val}' for val in data[sense]['values']],
            name=sense.capitalize()
        ),
        row=row,
        col=col
    )

# 统一布局设置
fig.update_layout(
    showlegend=False,
    plot_bgcolor='#f9f9f9',
    paper_bgcolor='#f9f9f9',
    font=dict(
        family="Times New Roman, Times, serif",
        size=12,
        color="black"
    ),
    title_font=dict(
        family="Times New Roman, Times, serif",
        size=14,
        color="black"
    ),
    margin=dict(l=50, r=50, b=50, t=80),
    width=1500,
    height=900
)

# 设置极坐标参数
for i in range(1, 6):
    fig.update_polars(
        hole=0.1,
        radialaxis=dict(
            visible=True,
            tickfont=dict(
                family="Times New Roman, Times, serif",
                size=12,
                color="black"
            ),
            gridcolor='rgba(0, 0, 0, 0.1)',
            linecolor='rgba(0, 0, 0, 0.1)',
            angle=90  # 调整角度标签位置
        ),
        angularaxis=dict(
            gridcolor='rgba(0, 0, 0, 0.1)',
            linecolor='rgba(0, 0, 0, 0.1)',
            rotation=90,
            direction='clockwise',
            tickfont=dict(
                family="Times New Roman, Times, serif",
                size=12,
                color="black"
            )
        ),
        row=(i+2)//3, col=(i-1)%3+1 if i<4 else (i-4)//3+1
    )

# 保存并显示

fig.show()