# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CXa1zpkYmsXuNDQBj2ouaMtjeGLpnYY1
"""

import json
import torch
from sentence_transformers import SentenceTransformer
import logging
from typing import List, Dict, Optional, Set, Tuple
import os
import re
import jieba
import numpy as np
import pandas as pd
from datetime import datetime
from transformers import AutoTokenizer, AutoModel

class BatchTokenizer:
    def __init__(self, model_name: str = "ethanyt/guwenbert-base"):
        """初始化分词器

        Args:
            model_name: 预训练模型名称，默认使用GuwenBERT
        """
        try:
            # 加载GuwenBERT模型和分词器
            self.tokenizer = AutoTokenizer.from_pretrained(model_name)
            self.model = AutoModel.from_pretrained(model_name)
            print("GuwenBERT模型加载成功")

            # 初始化感官词典
            self._init_sensory_dict()

        except Exception as e:
            print(f"模型加载失败: {str(e)}")
            print("请确保已安装transformers库并且网络连接正常")
            raise

    def load_annotations(self, annotation_file: str):
        """加载已有的标注数据

        Args:
            annotation_file: 包含已标注数据的CSV文件路径
        """
        try:
            df = pd.read_csv(annotation_file)
            print(f"正在加载已标注数据: {annotation_file}")

            # 处理每个感官类别的标注
            categories = {
                '视觉词': 'visual',
                '味觉词': 'taste',
                '嗅觉词': 'smell',
                '触觉词': 'touch',
                '听觉词': 'sound'
            }

            # 更新感官词典
            for zh_name, en_name in categories.items():
                if zh_name in df.columns:
                    words = set()
                    for annotation in df[zh_name].dropna():
                        if isinstance(annotation, str):
                            words.update(w.strip() for w in annotation.split(','))
                    # 添加到现有词典
                    self.sensory_dict[en_name].update(words)
                    # 添加到jieba分词器
                    for word in words:
                        jieba.add_word(word)

            print("\n已更新感官词典:")
            for en_name, words in self.sensory_dict.items():
                print(f"- {en_name}: {len(words)}个词")

        except Exception as e:
            print(f"加载标注数据失败: {str(e)}")
            raise

    def analyze_text_with_annotations(self, text: str) -> Dict[str, List[str]]:
        """使用更新后的词典分析文本

        Args:
            text: 输入文本

        Returns:
            各个感官类别的词列表
        """
        tokens = self.tokenize_text(text)
        return self.analyze_sensory_words(tokens)

    def _init_sensory_dict(self):
        """初始化感官词典"""
        self.sensory_dict = {
            "visual": {
                "翠", "碧", "白", "素","轻尘", "紫饼","紫玉丛","翠峰顶","黄金粉","绿乳","松花","玄", "黄", "青箬","玉色尘","水清","乳花","紫", "金", "银", "玉乳","青",'乌',"玉","绿丛",'瓯',"虎跑泉","枣花","圭璧","烟岚色","丑","嫩色"
                "雪色", "月华", "云母", "玉华", "烟霞", "琉璃", "琥珀", "霜华", "紫茗","晓露","烟树","清泉","清露","波纹","绿华",'翠筠'
                "瑶草", "琼蕊", "鹰嘴", "旗枪", "雀舌", "莲心", "紫笋", "金芽","白玉","红纱","黄蕊色","春露","红云","轻烟","金刀","紫芽","白蕊","石碾"
                "玉乳", "凝脂", "浮光", "流华", "错落", "圆如月", "枪旗展",'饼','球','矛','珠','菊花','条','片','针','碗','臼','臼形','柱','枕','砖',
                '平直','平伏','平整','苗直','苗条','松泡','松散','松碎','空松','空泡','轻飘','飘薄','细长','细秀','细紧','细圆','细嫩','茸毫','金毫','肥壮',
                '肥嫩','显毫','紧秀','紧直','紧实','挺秀','挺直','重实','团块','团粒',"清霞",'圆头','圆直','圆紧','圆整','钝圆','扁平','扁条','扁削','粗','粗大','粗老',
                '粗杂','粗壮','粗松','粗糙','毛糙','短','短秃','短钝','短碎','宽','宽条','宽扁','宽松','嫩匀','毫尖','嫩尖','包芽','浑条','浑圆','匀齐','匀净','露梗',
                '露白梗','露老梗','露黄','露筋','折皱','鱼眼','端正','卷曲','雄壮','雀舌','勾曲','卷','卷边','糊状','光亮','光洁','光润','光滑','乌条','暗','暗条',
                '乌黑','乌黑油润','乌润','红','红茎','红筋','棕红','棕润','棕褐','鲜绿','嫩绿','翠绿','绿','绿翠','苍绿','三绿','青绿','墨绿','绿润',
                '起霜','霜','银白',"绿趸",'银灰','灰白',"紫萼",'灰绿','灰暗','黑润','黑褐','褐','糙米色','泛红','陈暗','走色','焦黄','焦斑','枯灰','枯红','枯松','枯黄',
                '枯棕','枯褐','枯暗','阴光','花杂','花渣','花瓣','末','沫','茶汤','明净','明亮','鲜明','鲜艳','清澈','清淡','红汤','红亮','红艳',
                '红褐','玫瑰红','棕红','金黄','金圈','栗褐','粉红','乳白','浅红','姜黄','嫩黄','橙黄','黄亮','棕黄','黄绿','黄暗',"黄金碾"
                '黄熟','暗红','黑褐','杏黄','鹅黄','浅黄','浅薄','陈暗',"紫霞",'浑浊','沉淀','起釉',"碗花","绿髓","金饼","琼液","云芽","建溪春","绿尘","云团"
            },
            "taste": {
                "甘", "苦", "涩", "鲜", "醇", "爽", "厚", "薄", "烈", "柔","汤嫩","甘香"
                "甜","润", "清", "酽", "淡", "回甘", "生津", "锁喉", "收敛","活水"
                "糙米","蜜韵", "兰底", "岩骨", "陈韵", "木质", "果酸", '浓郁',"奇香"
                "海苔", "冰糖", "药香", "火工", "水味", "舌底鸣泉","细腻",'鲜灵','茶味','味长','味浓',
                '味淡','味短','味强','柔和','平和','平薄','鲜美','鲜浓','鲜爽','鲜甜','鲜醇','嫩爽','嫩鲜','醇正',
                '醇和','醇厚','醇爽','浓厚','浓烈','浓涩','浓爽','浓强','浓醇','厚实','高爽','甜润',
                '甜和','甜爽','酸','甜醇','韵味','粗涩','粗淡','粗薄','清爽','清淡','贫乏',
                '乏味','火味','老火','平淡','生味','青涩','苦味','苦涩','味软','熟味','生涩','异味',
                '走味','陈气','失风','陈熟','滞钝','钝熟','花香','辛涩','雪水茶',"青琼","嫩汤"
            },
            "smell": {
                "芳", "馨", "馥", "幽", "清", "烈", "郁", '香','甜香',"芳气","新烟","晓烟","芳烟"
                '毫香','嫩栗香', '板栗香','嫩香','清香','南瓜香','秋香','幽香','玫瑰香','松烟香','桂花香',
                "栗香", "兰气", '橘香', '音韵','馥郁','持久','足火香','炒麦香',"蘋沫香","香泛","薄兰芷"
                "桂香", "松烟", "梅韵", "枣甜", "蜜香", "乳香", "樟香", "药香","良","积芳"
                "陈香", "火香", "焦糖", "青草", "腥气", "霉味", "日晒", "炭焙","香尘","活火"
                "冷香", "暗香", "浮香", "透天香", "碗盖香", "挂杯香",'透兰','茉莉香','透素','高纯','香高','香短',
                '香浮','纯正','纯和','茶香','陈香','陈熟','火香','老火','青气','生青','烟',"香泉","杉脂香",""
            },
            "touch": {
                "滑", "润", "冷", "燥", "凝", "粘", "糙", "砂", "绵", "刺","研膏","碾"
                "骨鲠", "化感", "收敛", "生涩", "顺滑", "稠厚", "米汤感","蒸","煮"
                "丝绸质", "颗粒感", "胶质感", "压舌", "挂齿", "砂感", "喉韵","炙花脯"
                "针刺", "温润", "冰凉", "炙手", "揉捻", "绵密", "板结","春风","研","轻如云"
            },
            "sound": {
                "松声", "泉鸣", "雷音", "碾声", "竹籁", "雨打", "鼎沸","泉声","碾处"
                "炭爆", "杵音", "罗筛", "瓯击", "瀑落", "鹤唳", "蝉噪","声如雷","鸣玉甃"
                "夜雨", "松涛", "竹炉响", "蟹眼声", "鱼目沸", "涌泉连珠","玉泉沸","鱼眼"
                "秋风劲", "竹间沥", "冰裂", "雪落", "更漏", "泠泠","潺潺","蟹目", "凿石","凿","潺湲声"
            }
        }

        # 将感官词添加到jieba分词器中
        for words in self.sensory_dict.values():
            for word in words:
                jieba.add_word(word)

        print("感官词典加载成功")

    def analyze_sensory_words(self, tokens: List[str]) -> Dict[str, List[str]]:
        """分析文本中的感官词

        Args:
            tokens: 分词后的词列表

        Returns:
            各个感官类别中找到的词
        """
        result = {
            "visual": [],
            "taste": [],
            "smell": [],
            "touch": [],
            "sound": []
        }

        for token in tokens:
            for sense, words in self.sensory_dict.items():
                if token in words:
                    result[sense].append(token)

        return result

    def _init_punctuation(self):
        """初始化标点符号列表"""
        self.punctuation = set([
            '。', '，', '、', '；', '：', '？', '！', '…', '—', '·', '‧',
            '"', '"', ''', ''', '〝', '〞', '（', '）', '〈', '〉', '《', '》',
            '【', '】', '『', '』', '「', '」', '﹁', '﹂', '﹃', '﹄',
            '〔', '〕', '…', '︵', '︶', '︷', '︸', '︹', '︺',
            '︻', '︼', '︽', '︾', '︿', '﹀', '％', '℃', '﹕',
            '．', '～', '‥', '∵', '∴', '☆', '※', '×', '○', '●',
            '◎', '◇', '◆', '□', '■', '△', '▲', '▽', '▼',
            '※', '〆', '↑', '↓', '←', '→', '↖', '↗', '↙',
            '↘', '↔', '↕', '＃', '＆', '＠', '＼', '︳', '︴',
            '﹏', '﹋', '﹌', '﹍', '﹎', '﹊', '﹉', '﹐', '﹑',
            '﹒', '﹔', '﹕', '﹖', '﹗', '﹟', '﹠', '﹡', '﹢',
            '﹣', '﹤', '﹥', '﹦', '﹨', '﹩', '﹪', '﹫',
            '～', '｜', '｛', '｝', '｢', '｣',
            # 英文标点
            ',', '.', ':', ';', '?', '!', '(', ')', '[', ']', '{', '}',
            '/', '\\', '|', '@', '#', '$', '%', '^', '&', '*', '-', '_',
            '+', '=', '<', '>', '`', '~', '"', '\''
        ])

    def remove_punctuation(self, text: str) -> str:
        """去除文本中的标点符号

        Args:
            text: 输入文本

        Returns:
            去除标点符号后的文本
        """
        return ''.join(char for char in text if char not in self.punctuation)

    def _init_jieba(self):
        """初始化jieba分词器并添加自定义词典"""
        # 添加古文常用词
        custom_words = [
            # 虚词
            '之', '乎', '其', '所', '者', '也', '矣', '焉', '耳', '春山','谷雨','惊蛰',
            '清明'
            # 常见词组
            '南方', '天下', '圣人', '君子', '四方', '万物', '天地', '日月',
            '上下', '春秋', '诸侯', '圣贤', '古今', '礼乐', '山川',
            # 茶相关词组
            '苦茶', '香茶', '茶道', '茶经', '茶具', '茶叶', '茶树', '茶汤',
            '煮茶', '品茶', '啜茶', '茗茶', '茶事', '茶器', '茶品', '茶性',
            '口甘', '甘','甘香','神爽','神','烹茶','煮茶','煎茶','泡茶',
            # 常见动词组合
            '饮之', '食之', '取之', '用之', '观之', '视之', '闻之', '知之',
            '得之', '失之', '言之', '论之', '述之', '记之', '载之', "翠", "碧", "白", "素", "玄", "黄", "紫", "金", "银", "青",'乌', "雪色", "月华", "云母", "玉华", "烟霞", "琉璃", "琥珀", "霜华",
            "瑶草", "琼蕊", "鹰嘴", "旗枪", "雀舌", "莲心", "紫笋", "金芽",
            "玉乳", "凝脂", "浮光", "流华", "错落", "圆如月", "枪旗展",'饼','球','矛','珠','菊花','条','片','针','碗','臼','臼形','柱','枕','砖',
            '平直','平伏','平整','苗直','苗条','松泡','松散','松碎','空松','空泡','轻飘','飘薄','细长','细秀','细紧','细圆','细嫩','茸毫','金毫','肥壮',
            '肥嫩','显毫','紧秀','紧直','紧实','挺秀','挺直','重实','团块','团粒','圆头','圆直','圆紧','圆整','钝圆','扁平','扁条','扁削','粗','粗大','粗老',
            '粗杂','粗壮','粗松','粗糙','毛糙','短','短秃','短钝','短碎','宽','宽条','宽扁','宽松','嫩匀','毫尖','嫩尖','包芽','浑条','浑圆','匀齐','匀净','露梗',
            '露白梗','露老梗','露黄','露筋','折皱','鱼眼','端正','卷曲','雄壮','雀舌','勾曲','卷','卷边','糊状','光亮','光洁','光润','光滑','乌条','暗','暗条',
            '乌黑','乌黑油润','乌润','红','红茎','红筋','棕红','棕润','棕褐','鲜绿','嫩绿','翠绿','绿','绿翠','苍绿','三绿','青绿','墨绿','绿润',
            '起霜','霜','银白','银灰','灰白','灰绿','灰暗','黑润','黑褐','褐','糙米色','泛红','陈暗','走色','焦黄','焦斑','枯灰','枯红','枯松','枯黄',
            '枯棕','枯褐','枯暗','阴光','花杂','花渣','花瓣','末','沫','茶汤','明净','明亮','鲜明','鲜艳','清澈','清淡','红汤','红亮','红艳',
            '红褐','玫瑰红','棕红','金黄','金圈','栗褐','粉红','乳白','浅红','姜黄','嫩黄','橙黄','黄亮','棕黄','黄绿','黄暗',
            '黄熟','暗红','黑褐','杏黄','鹅黄','浅黄','浅薄','陈暗','浑浊','沉淀','起釉', "甘", "苦", "涩", "鲜", "醇", "爽", "厚", "薄", "烈", "柔",
                "甜","润", "清", "酽", "淡", "回甘", "生津", "锁喉", "收敛",
                "糙米","蜜韵", "兰底", "岩骨", "陈韵", "木质", "果酸", '浓郁'
                "海苔", "冰糖", "药香", "火工", "水味", "舌底鸣泉","细腻",'鲜灵','茶味','味长','味浓',
                '味淡','味短','味强','柔和','平和','平薄','鲜美','鲜浓','鲜爽','鲜甜','鲜醇','嫩爽','嫩鲜','醇正',
                '醇和','醇厚','醇爽','浓厚','浓烈','浓涩','浓爽','浓强','浓醇','厚实','高爽','甜润',
                '甜和','甜爽','酸','甜醇','韵味','粗涩','粗淡','粗薄','清爽','清淡','贫乏',
                '乏味','火味','老火','平淡','生味','青涩','苦味','苦涩','味软','熟味','生涩','异味',
                '走味','陈气','失风','陈熟','滞钝','钝熟','花香','辛涩','', "芳", "馨", "馥", "幽", "清", "烈", "郁", '香','甜香',
                '毫香','嫩栗香', '板栗香','嫩香','清香','南瓜香','秋香','幽香','玫瑰香','松烟香','桂花香',
                "栗香", "兰气", '橘香', '音韵','馥郁','持久','足火香','炒麦香',
                "桂香", "松烟", "梅韵", "枣甜", "蜜香", "乳香", "樟香", "药香",
                "陈香", "火香", "焦糖", "青草", "腥气", "霉味", "日晒", "炭焙",
                "冷香", "暗香", "浮香", "透天香", "碗盖香", "挂杯香",'透兰','茉莉香','透素','高纯','香高','香短',
                '香浮','纯正','纯和','茶香','陈香','陈熟','火香','老火','青气','生青','烟', "滑", "润", "冷", "燥", "凝", "粘", "糙", "砂", "绵", "刺",'碾'
                "骨鲠", "化感", "收敛", "生涩", "顺滑", "稠厚", "米汤感",
                "丝绸质", "颗粒感", "胶质感", "压舌", "挂齿", "砂感", "喉韵",
                "针刺", "温润", "冰凉", "炙手", "揉捻", "绵密", "板结","松声", "泉鸣", "雷音", "碾声", "竹籁", "雨打", "鼎沸",
                "炭爆", "杵音", "罗筛", "瓯击", "瀑落", "鹤唳", "蝉噪",
                "夜雨", "松涛", "竹炉响", "蟹眼声", "鱼目沸", "涌泉连珠",
                "秋风劲", "竹间沥", "冰裂", "雪落", "更漏"
        ]

        for word in custom_words:
            jieba.add_word(word)

        print("自定义词典加载成功")

    def tokenize_text(self, text: str) -> List[str]:
        """使用GuwenBERT分词器进行分词，并合并连续字符为词组

        Args:
            text: 输入文本

        Returns:
            分词结果列表
        """
        try:
            # 首先使用自定义词典进行分词
            words = []
            i = 0
            text_len = len(text)

            while i < text_len:
                matched = False
                # 尝试最长匹配
                for length in range(4, 0, -1):  # 从4字词到单字
                    if i + length <= text_len:
                        word = text[i:i+length]
                        # 检查是否在感官词典中
                        if any(word in word_set for word_set in self.sensory_dict.values()):
                            words.append(word)
                            i += length
                            matched = True
                            break

                if not matched:
                    # 如果没有匹配到感官词，使用GuwenBERT分词
                    if i < text_len:
                        words.append(text[i])
                    i += 1

            return words

        except Exception as e:
            print(f"分词失败: {str(e)}")
            return []

    def get_sentence_embedding(self, text: str) -> np.ndarray:
        """获取文本的向量表示"""
        try:
            # 编码文本，设置最大长度
            max_length = 512  # BERT模型的标准最大长度
            inputs = self.tokenizer(
                text,
                return_tensors="pt",
                padding=True,
                truncation=True,
                max_length=max_length
            )

            # 获取模型输出
            with torch.no_grad():
                outputs = self.model(**inputs)

            # 使用最后一层的[CLS]标记作为句子表示
            sentence_embedding = outputs.last_hidden_state[0][0].numpy()
            return sentence_embedding

        except Exception as e:
            print(f"获取向量表示失败: {str(e)}")
            return np.zeros(768)  # 返回零向量作为默认值

    def process_file(self, file_path: str) -> List[Dict]:
        """处理文件中的文本

        Args:
            file_path: 文本文件路径

        Returns:
            处理结果列表
        """
        try:
            # 读取JSON文件
            if file_path.endswith('.json'):
                with open(file_path, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                # 提取所有content字段
                texts = []
                for item in data.values():
                    if isinstance(item, dict) and 'content' in item:
                        texts.append(item['content'])
            # 读取TXT文件
            else:
                with open(file_path, 'r', encoding='utf-8') as f:
                    texts = [line.strip() for line in f if line.strip()]

            results = []
            # 处理每一行文本
            for i, text in enumerate(texts, 1):
                # 直接分词，不去除标点
                tokens = self.tokenize_text(text)
                # 获取句向量
                embedding = self.get_sentence_embedding(text)

                # 分析感官词
                sensory_analysis = self.analyze_sensory_words(tokens)

                results.append({
                    'index': i,
                    'original': text,
                    'tokens': tokens,
                    'embedding': embedding.tolist(),
                    'sensory_words': sensory_analysis,
                    'sensory_stats': {
                        category: len(words)
                        for category, words in sensory_analysis.items()
                    }
                })

            return results

        except Exception as e:
            print(f"处理文件时出错: {str(e)}")
            return []

    def save_results(self, results: List[Dict], output_format: str = 'csv'):
        """保存处理结果

        Args:
            results: 处理结果列表
            output_format: 输出格式，'csv', 'json' 或 'txt'
        """
        if not results:
            print("没有结果可保存")
            return

        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

        if output_format == 'csv':
            # 准备DataFrame数据
            df_data = []
            for result in results:
                sensory_info = {
                    f'{sense}词': ', '.join(words) if words else '无'
                    for sense, words in result['sensory_words'].items()
                }

                df_data.append({
                    '序号': result['index'],
                    '原文': result['original'],
                    '分词结果': ' | '.join(result['tokens']),
                    '词数': len(result['tokens']),
                    **sensory_info,
                    '视觉词数': result['sensory_stats']['visual'],
                    '味觉词数': result['sensory_stats']['taste'],
                    '嗅觉词数': result['sensory_stats']['smell'],
                    '触觉词数': result['sensory_stats']['touch'],
                    '听觉词数': result['sensory_stats']['sound']
                })

            # 创建DataFrame并保存为CSV
            df = pd.DataFrame(df_data)
            output_file = f'tokenized_results_{timestamp}.csv'
            df.to_csv(output_file, index=False, encoding='utf-8-sig')
            print(f"\n结果已保存至CSV文件: {output_file}")

        elif output_format == 'json':
            # 准备JSON数据
            json_data = {}
            for result in results:
                json_data[f"text{result['index']}"] = {
                    "original": result['original'],
                    "processed": result['processed'],
                    "tokens": result['tokens'],
                    "token_count": len(result['tokens']),
                    "embedding": result['embedding'],
                    "sensory_analysis": result['sensory_words'],
                    "sensory_stats": result['sensory_stats']
                }

            # 保存为JSON文件
            output_file = f'tokenized_results_{timestamp}.json'
            with open(output_file, 'w', encoding='utf-8') as f:
                json.dump(json_data, f, ensure_ascii=False, indent=2)
            print(f"\n结果已保存至JSON文件: {output_file}")

        else:  # txt格式
            output_file = f'tokenized_results_{timestamp}.txt'
            with open(output_file, 'w', encoding='utf-8') as f:
                for result in results:
                    f.write(f"\n{'-' * 60}\n")
                    f.write(f"序号: {result['index']}\n")
                    f.write(f"原文: {result['original']}\n")
                    f.write(f"分词: {' | '.join(result['tokens'])}\n")
                    f.write(f"词数: {len(result['tokens'])}\n")
                    f.write("\n感官词分析:\n")
                    for sense, words in result['sensory_words'].items():
                        sense_name = {
                            'visual': '视觉',
                            'taste': '味觉',
                            'smell': '嗅觉',
                            'touch': '触觉',
                            'sound': '听觉'
                        }[sense]
                        f.write(f"{sense_name}词({len(words)}个): {', '.join(words) if words else '无'}\n")

            print(f"\n结果已保存至文本文件: {output_file}")

def main():
    """主函数"""
    print("\n" + "=" * 80)
    print("文本分词与感官词分析工具 (支持已标注数据)")
    print("=" * 80)
    print("\n使用说明:")
    print("1. 输入要处理的文件路径（支持.txt或.json格式）")
    print("2. 程序将自动处理文件中的文本，进行分词和感官词分析")
    print("3. 结果将保存为CSV、JSON或TXT格式")
    print("\n" + "=" * 80)

    try:
        tokenizer = BatchTokenizer()

        # 询问是否加载已标注数据
        use_annotations = input("\n是否加载已标注数据？(y/n): ").lower() == 'y'
        if use_annotations:
            annotation_file = input("请输入已标注数据文件路径: ").strip()
            if os.path.exists(annotation_file):
                tokenizer.load_annotations(annotation_file)
            else:
                print(f"错误：找不到文件 {annotation_file}")
                return

    except Exception as e:
        print(f"初始化失败: {str(e)}")
        return

    while True:
        # 获取文件路径
        file_path = input("\n请输入文件路径 (输入q退出): ").strip()

        if file_path.lower() == 'q':
            print("程序已退出")
            break

        if not os.path.exists(file_path):
            print(f"错误：找不到文件 {file_path}")
            continue

        # 处理文件
        results = tokenizer.process_file(file_path)

        if not results:
            continue

        # 显示结果预览
        print("\n处理结果预览:")
        print("=" * 80)
        preview_count = min(3, len(results))
        for i in range(preview_count):
            result = results[i]
            print(f"\n原文: {result['original']}")
            print(f"分词: {' | '.join(result['tokens'])}")
            print(f"词数: {len(result['tokens'])}")
            print("\n感官词分析:")
            for sense, words in result['sensory_words'].items():
                sense_name = {
                    'visual': '视觉',
                    'taste': '味觉',
                    'smell': '嗅觉',
                    'touch': '触觉',
                    'sound': '听觉'
                }[sense]
                print(f"{sense_name}词({len(words)}个): {', '.join(words) if words else '无'}")

        if len(results) > preview_count:
            print("\n... (更多结果请查看输出文件)")

        # 保存结果
        print("\n请选择保存格式:")
        print("1: CSV (默认)")
        print("2: JSON")
        print("3: TXT")
        save_format = input("请选择 (1/2/3): ").strip()

        if save_format == '2':
            output_format = 'json'
        elif save_format == '3':
            output_format = 'txt'
        else:
            output_format = 'csv'

        tokenizer.save_results(results, output_format)

        # 询问是否继续
        if input("\n是否继续处理其他文件？(y/n): ").lower() != 'y':
            print("程序已退出")
            break

if __name__ == "__main__":
    main()