# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/118q0PowmuA8g-uoNw7vA2hSSIAGsyXkg
"""

import plotly.graph_objects as go
from plotly.subplots import make_subplots

# 配置数据
sense_types = ['视觉', '嗅觉', '味觉', '触觉', '听觉']
colors = [
    'rgba(121, 199, 183, 0.8)',  # 浅青绿色
    'rgba(97, 142, 204, 0.8)',   # 蓝色
    'rgba(241, 109, 122, 0.8)',  # 红色
    'rgba(246, 185, 128, 0.8)',  # 橙色
    'rgba(188, 216, 105, 0.8)'   # 黄绿色
]

datasets = [
    {'name': '词汇总数', 'values': [189, 80, 36, 33, 14], 'y_range': [0, 200]},
    {'name': '平均每句词数', 'values': [0.43, 0.18, 0.08, 0.07, 0.03], 'y_range': [0, 0.5]},
    {'name': '占比', 'values': [53.69, 22.73, 10.23, 9.38, 3.98], 'y_range': [0, 60]},
    {'name': '包含该类词汇的句子比例', 'values': [32.66, 14.41, 6.76, 5.63, 2.48], 'y_range': [0, 35]}
]

# 创建2x2子图布局
fig = make_subplots(
    rows=2,
    cols=2,
    subplot_titles=[d['name'] for d in datasets],
    vertical_spacing=0.15,
    horizontal_spacing=0.1
)

# 添加每个图表数据
for i, dataset in enumerate(datasets):
    row = (i // 2) + 1
    col = (i % 2) + 1

    fig.add_trace(
        go.Bar(
            x=sense_types,
            y=dataset['values'],
            marker_color=colors,
            marker_line_color='rgba(0,0,0,0)',
            opacity=0.8,
            showlegend=False
        ),
        row=row,
        col=col
    )

    # 设置每个子图的Y轴范围
    fig.update_yaxes(range=dataset['y_range'], row=row, col=col)

# 统一布局设置
fig.update_layout(
    plot_bgcolor='white',
    paper_bgcolor='white',
    margin=dict(l=40, r=40, b=40, t=80),
    width=1200,
    height=800,
    font=dict(family="Arial", size=12),
    annotations=[
        dict(
            x=0.5,
            y=-0.15,
            showarrow=False,
            text="五感类型",
            xref="paper",
            yref="paper"
        )
    ]
)

# 设置子图公共属性
fig.update_xaxes(showgrid=False, tickangle=0)
fig.update_yaxes(showgrid=True, gridcolor='#e0e0e0')
fig.update_annotations(font_size=14)  # 子图标题字号

# 输出到HTML文件
fig.write_html("five_senses_dashboard.html")

# 显示图表
fig.show()