# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IwsnwEWkk4J7c2FBhZyQ0d-NZgV0RpNf
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Updated Data
data = {
    "Dynasty": ["Tang", "Tang", "Song", "Song", "Ming"],
    "Water Type": ["Spring Water", "Well Water", "Spring Water", "Well Water", "Spring Water"],
    "Frequency": [21, 5, 24, 6, 14]
}

# Create DataFrame
df = pd.DataFrame(data)

# Set Seaborn style
sns.set_theme(style="whitegrid")

# Create a larger bar plot
plt.figure(figsize=(14, 8))  # Adjust the figure size
bar_plot = sns.barplot(
    data=df,
    x="Dynasty",
    y="Frequency",
    hue="Water Type",
    palette=["green", "orange"]  # Colors for Spring Water and Well Water
)

# Add labels to the axes
plt.xlabel("Dynasty", fontsize=14)
plt.ylabel("Frequency", fontsize=14)

# Add values on top of bars
for container in bar_plot.containers:
    bar_plot.bar_label(container, fmt='%d', label_type='edge', fontsize=12)

# Adjust legend
plt.legend(title="Water Type", title_fontsize=12, fontsize=11)

# Display the plot
plt.tight_layout()
plt.show()